### ISSUE TITLE
channel suggestion

### ISSUE THREAD

**Issue by ynshung** [agmmnn/awesome-blender#1]
Hello, just wanted to let you know there's a channel called [Daniel Krafft - DSO](https://www.youtube.com/channel/UCojEXrCBzO-cP2N5YlRcrWw) that contains some helpful blender videos such as 100/150 blender tips, 100 addons and blender tutorial list that you can refer or add into the catalog. Keep up the good work!

**Comment by agmmnn** [comment]
I added this channel(and a few more) on Youtube Channels, thank you for your suggestion. :)
