### ISSUE TITLE
Link addition to Free Stocks/Cutouts

### ISSUE THREAD

**Issue by CleanArchviz** [agmmnn/awesome-blender#23]
Add these two links https://www.vishopper.com/cut-out-people/ for cut out people

https://www.vishopper.com/cut-out-trees-and-plants for cut out trees.

You can use search to only show free images. All images have either a commercial license with model release or an editorial license. 

There are also sky images for use as backgrounds https://www.vishopper.com/sky-textures

**Comment by agmmnn** [comment]
thanks for contributions, will be added in the next commitment.
