### ISSUE TITLE
Suggestion: Add BlendyPose to Mocap/Animation

### ISSUE THREAD

**Issue by photoenix** [agmmnn/awesome-blender#27]
I found this addon by chance. Unfortunately it seems to be pretty unknown and I couldn't find any Tutorials for it. It is pretty awesome and deserves some exposure. Basically, I need someone to show me how to link the mocap points to a model/armature.
https://github.com/zonkosoft/BlendyPose

**Comment by agmmnn** [comment]
added, thanks for contribution.
