### ISSUE TITLE
More MoCap

### ISSUE THREAD

**Issue by fgiering** [agmmnn/awesome-blender#31]
You could list https://github.com/BandaiNamcoResearchInc/Bandai-Namco-Research-Motiondataset as well.

**Comment by Jogai** [comment]
You could make a pr ;-)

**Comment by fgiering** [comment]
thats a away to much effort for adding just a single link

**Comment by Jogai** [comment]
That's how awesome lists work.. And you can do it all from within the browser with github, so its not that much effort..
