### ISSUE TITLE
Distinguish Freeware From Free Software

### ISSUE THREAD

**Issue by ldo** [agmmnn/awesome-blender#9]
Might I suggest you draw a clear distinction between proprietary [freeware](https://en.wikipedia.org/wiki/Freeware) and non-proprietary [Free software](https://en.wikipedia.org/wiki/Free_software)? For example, you describe TerreSculptor as “completely free”, yet it does not seem to respect the [Four Freedoms](https://www.gnu.org/philosophy/free-sw.en.html) of Free software.

**Comment by agmmnn** [comment]
Right, thank you! Actually, I do not know much about this subject. Such things like **copyright, license, limitations, etc.** on the list should be corrected or more explicit, this issue can be kept open if someone wants to contribute.

**Comment by bestman8** [comment]
all lisence info i found for the ai powered things 
waifu2x under ai powered is under the mit license 
PIFuHD is under the CC-BY-NC-SA-4.0 license 
PaintsChainer is under the mit license 
3d-photo-inpainting is under the mit license
DAIN is under the mit license 
Let'sEnhance.io is under the mit license
while talking about ai powered also add video2x to that list https://video2x.org/ https://github.com/k4yt3x/video2x/tree/4.7.0 under the GNU General Public License v3.0  in short gplv3

**Comment by bestman8** [comment]
all lisence info i have found for render engines 
appleseed is under the mit lisence the blender addon under the mit lisence i dont know how but that is what i found 
luxcore the blender addon is under the GNU General Public License v3.0 or the gplv3 lisence the stand alone under Apache License Version 2.0
e-cycles has to be under GNU General Public License v3.0 or higher  or gplv3 or higher just like all blender addons should be 
radeon prorender is under the  Apache License, Version 2.0
render man is under the mit lisence
i wasn't able to find a lisence for redshift
same for octane but the custom blender build without the octane server is  GNU General Public License v3.0 or the gplv3 lisence

**Comment by bestman8** [comment]
i might try to find more tommorow

**Comment by agmmnn** [comment]
thank you so much @bestman8. i'll add them in the next commit.

**Comment by agmmnn** [comment]
I'm thinking of doing something like [this](https://github.com/agmmnn/awesome-blender/issues/14#issuecomment-932496232) in the next commits. Thanks for helps @bestman8.

This issue can be continued to be discussed here -> #14
